enum BAMER_ROLE {
  # A developer
  DEV
  # A sale
  SALE
  # A member of growth team
  GROWTH
  # An admin fi
  ADMIN
}

# represent a bamer
type Bamer {
  id: ID!
  # the bamer role
  role: BAMER_ROLE
  # the bamer full name
  name: String @deprecated(reason: "Use firstName and lastName instead")
  # the bamer firstName
  firstName: String
  # the bamer lastName
  lastName: String
  # the bamer email
  email: String
  # the books currently borrowed by the bamer
  booksCurrentlyBorrowed: [Book]
}
