# represents the map of the fields that will derectly be available on top of the graphQL query
type Query {
  # a bammer, by id
  bammer: Bammer
  # all the bammer
  allBammers: [Bammer]
  # a book, by id
  book: Book
  # all the book
  allBooks: [Book]
}