enum BAMMER_ROLE {
  # A developer
  DEV
  # A sale
  SALE
  # A member of growth team
  GROWTH
  # An admin fi
  ADMIN
}

# represent a bammer
type Bammer {
  id: ID!
  # the bammer role
  role: BAMMER_ROLE
  # the bammer full name
  name: String @deprecated(reason: "Use firstName and lastName instead")
  # the bammer firstName
  firstName: String
  # the bammer lastName
  lastName: String
  # the bammer email
  email: String
  # the books currently borrowed by the bammer
  booksCurrentlyBorrowed: [Book]
}
