# represent a book
type Book {
  # the book id
  id: ID!
  # the book title
  name: String!
  # the book author
  author: String
  # the bammer that may have borrowed the book
  currentlyBorrowedBy: Bammer
}